imports:
  - { resource: shared.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WsFramework\Service\HelpService\TransportStrategyService\OpenRpcTransportStrategy:
    arguments:
      $namespaceMethods: '\WsFramework\Action\Method\FfmpegQueue'

  WsFramework\Service\HelpService\TransportStrategyService\TransportStrategyInterface:
    alias: WsFramework\Service\HelpService\TransportStrategyService\OpenRpcTransportStrategy

  WsFramework\Service\FfmpegQueueService\FfmpegQueueService:
    public: true
