networks:
  srv-queue:
    name: srv-queue
    ipam:
      config:
        - subnet: ${SUBNET}

volumes:
  nats_storage:

services:
  nats:
    build:
      context: ./container/nats
    command: -c /etc/nats/nats-server.conf
    volumes:
      - nats_storage:/nats/storage
    networks:
      srv-queue:

  nats-box:
    container_name: container_natsbox
    image: natsio/nats-box:latest
    command: sh -c "sleep infinity"
    environment:
      NATS_URL: nats://nats:4222
    networks:
      srv-queue:
    depends_on:
      - nats

  wsframework:
    container_name: container_wsframework
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
    build:
      context: ./container/php8.4
      args:
        PHP_INI: ${PHP_INI}
    volumes:
      - ./:/var/www/html
    ports:
      - '${NATS_JETSTREAM_HTTP_PORT}:${NATS_JETSTREAM_HTTP_PORT}'
    networks:
      srv-queue:
        ipv4_address: ${WSFRAMEWORK_IP:-192.163.0.120}
    command: ${WSFRAMEWORK_COMMAND}
    env_file:
      - ./.env
    depends_on:
      - nats

  ffmpeg:
    container_name: container_ffmpeg
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 2048M
    build:
      context: ./container/ffmpeg
    volumes:
      - ./:/var/www/html
    networks:
      srv-queue:
        ipv4_address: ${FFMPEG_IP:-192.163.0.121}
    command: ${FFMPEG_COMMAND}
    env_file:
      - ./.env
    depends_on:
      - nats

  s3-worker:
    container_name: container_s3worker
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    build:
      context: ./container/php8.4
    volumes:
      - ./:/var/www/html
    networks:
      srv-queue:
    command: ${S3_WORKER_COMMAND}
    env_file:
      - ./.env
    depends_on:
      - nats
